name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.3.0
  http_interceptor: ^1.0.2
  http: ^0.13.3
  flutter_native_splash: ^2.0.5
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/bars/
    - lib/assets/images/inputs/
    - lib/assets/images/
    - assets/images/
    - .env

# Configuração para o flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "lib/assets/images/logo-app.png"
  image_path: "lib/assets/images/logo-app.png"

# Configuração para o flutter_native_splash
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFAB6"
  image: assets/images/splash-logo.png
