INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (1, 'Brazil', 'Brasil', 'BR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (2, 'Afghanistan', 'Afeganistão', 'AF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (3, 'Albania', 'Albânia, Republica da', 'AL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (4, 'Algeria', 'Argélia', 'DZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (5, 'American Samoa', 'Samoa Americana', 'AS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (6, 'Andorra', 'Andorra', 'AD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (7, 'Angola', 'Angola', 'AO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (8, 'Anguilla', 'Anguilla', 'AI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (9, 'Antarctica', 'Antártida', 'AQ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (10, 'Antigua and Barbuda', 'Antigua e Barbuda', 'AG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (11, 'Argentina', 'Argentina', 'AR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (12, 'Armenia', 'Armênia, Republica da', 'AM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (13, 'Aruba', 'Aruba', 'AW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (14, 'Australia', 'Austrália', 'AU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (15, 'Austria', 'Áustria', 'AT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (16, 'Azerbaijan', 'Azerbaijão, Republica do', 'AZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (17, 'Bahamas', 'Bahamas, Ilhas', 'BS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (18, 'Bahrain', 'Bahrein, Ilhas', 'BH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (19, 'Bangladesh', 'Bangladesh', 'BD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (20, 'Barbados', 'Barbados', 'BB');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (21, 'Belarus', 'Belarus, Republica da', 'BY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (22, 'Belgium', 'Bélgica', 'BE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (23, 'Belize', 'Belize', 'BZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (24, 'Benin', 'Benin', 'BJ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (25, 'Bermuda', 'Bermudas', 'BM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (26, 'Bhutan', 'Butão', 'BT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (27, 'Bolivia', 'Bolívia', 'BO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (28, 'Bosnia and Herzegowina', 'Bósnia-herzegovina (Republica da)', 'BA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (29, 'Botswana', 'Botsuana', 'BW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (30, 'Bouvet Island', 'Bouvet, Ilha', 'BV');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (31, 'British Indian Ocean Territory', 'Território Britânico do Oceano Indico', 'IO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (32, 'Brunei Darussalam', 'Brunei', 'BN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (33, 'Bulgaria', 'Bulgária, Republica da', 'BG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (34, 'Burkina Faso', 'Burkina Faso', 'BF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (35, 'Burundi', 'Burundi', 'BI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (36, 'Cambodia', 'Camboja', 'KH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (37, 'Cameroon', 'Camarões', 'CM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (38, 'Canada', 'Canada', 'CA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (39, 'Cape Verde', 'Cabo Verde, Republica de', 'CV');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (40, 'Cayman Islands', 'Cayman, Ilhas', 'KY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (41, 'Central African Republic', 'Republica Centro-Africana', 'CF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (42, 'Chad', 'Chade', 'TD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (43, 'Chile', 'Chile', 'CL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (44, 'China', 'China, Republica Popular', 'CN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (45, 'Christmas Island', 'Christmas, Ilha (Navidad)', 'CX');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (46, 'Cocos (Keeling) Islands', 'Cocos (Keeling), Ilhas', 'CC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (47, 'Colombia', 'Colômbia', 'CO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (48, 'Comoros', 'Comores, Ilhas', 'KM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (49, 'Congo', 'Congo', 'CG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (50, 'Congo, the Democratic Republic of the', 'Congo, Republica Democrática do', 'CD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (51, 'Cook Islands', 'Cook, Ilhas', 'CK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (52, 'Costa Rica', 'Costa Rica', 'CR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (53, 'Cote d`Ivoire', 'Costa do Marfim', 'CI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (54, 'Croatia (Hrvatska)', 'Croácia (Republica da)', 'HR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (55, 'Cuba', 'Cuba', 'CU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (56, 'Cyprus', 'Chipre', 'CY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (57, 'Czech Republic', 'Tcheca, Republica', 'CZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (58, 'Denmark', 'Dinamarca', 'DK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (59, 'Djibouti', 'Djibuti', 'DJ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (60, 'Dominica', 'Dominica, Ilha', 'DM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (61, 'Dominican Republic', 'Republica Dominicana', 'DO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (62, 'East Timor', 'Timor Leste', 'TL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (63, 'Ecuador', 'Equador', 'EC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (64, 'Egypt', 'Egito', 'EG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (65, 'El Salvador', 'El Salvador', 'SV');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (66, 'Equatorial Guinea', 'Guine-Equatorial', 'GQ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (67, 'Eritrea', 'Eritreia', 'ER');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (68, 'Estonia', 'Estônia, Republica da', 'EE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (69, 'Ethiopia', 'Etiópia', 'ET');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (70, 'Falkland Islands (Malvinas)', 'Falkland (Ilhas Malvinas)', 'FK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (71, 'Faroe Islands', 'Feroe, Ilhas', 'FO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (72, 'Fiji', 'Fiji', 'FJ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (73, 'Finland', 'Finlândia', 'FI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (74, 'France', 'Franca', 'FR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (76, 'French Guiana', 'Guiana francesa', 'GF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (77, 'French Polynesia', 'Polinésia Francesa', 'PF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (78, 'French Southern Territories', 'Terras Austrais e Antárticas Francesas', 'TF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (79, 'Gabon', 'Gabão', 'GA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (80, 'Gambia', 'Gambia', 'GM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (81, 'Georgia', 'Georgia, Republica da', 'GE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (82, 'Germany', 'Alemanha', 'DE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (83, 'Ghana', 'Gana', 'GH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (84, 'Gibraltar', 'Gibraltar', 'GI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (85, 'Greece', 'Grécia', 'GR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (86, 'Greenland', 'Groenlândia', 'GL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (87, 'Grenada', 'Granada', 'GD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (88, 'Guadeloupe', 'Guadalupe', 'GP');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (89, 'Guam', 'Guam', 'GU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (90, 'Guatemala', 'Guatemala', 'GT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (91, 'Guinea', 'Guine', 'GN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (92, 'Guinea-Bissau', 'Guine-Bissau', 'GW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (93, 'Guyana', 'Guiana', 'GY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (94, 'Haiti', 'Haiti', 'HT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (95, 'Heard and Mc Donald Islands', 'Ilha Heard e Ilhas McDonald', 'HM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (96, 'Holy See (Vatican City State)', 'Vaticano, Estado da Cidade do', 'VA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (97, 'Honduras', 'Honduras', 'HN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (98, 'Hong Kong', 'Hong Kong', 'HK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (99, 'Hungary', 'Hungria, Republica da', 'HU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (100, 'Iceland', 'Islândia', 'IS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (101, 'India', 'Índia', 'IN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (102, 'Indonesia', 'Indonésia', 'ID');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (103, 'Iran (Islamic Republic of)', 'Ira, Republica Islâmica do', 'IR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (104, 'Iraq', 'Iraque', 'IQ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (105, 'Ireland', 'Irlanda', 'IE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (106, 'Israel', 'Israel', 'IL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (107, 'Italy', 'Itália', 'IT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (108, 'Jamaica', 'Jamaica', 'JM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (109, 'Japan', 'Japão', 'JP');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (110, 'Jordan', 'Jordânia', 'JO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (111, 'Kazakhstan', 'Cazaquistão, Republica do', 'KZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (112, 'Kenya', 'Quênia', 'KE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (113, 'Kiribati', 'Kiribati', 'KI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (114, 'Korea, Democratic People`s Republic of', 'Coreia, Republica Popular Democrática da', 'KP');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (115, 'Korea, Republic of', 'Coreia, Republica da', 'KR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (116, 'Kuwait', 'Kuwait', 'KW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (117, 'Kyrgyzstan', 'Quirguiz, Republica', 'KG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (118, 'Lao People`s Democratic Republic', 'Laos, Republica Popular Democrática do', 'LA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (119, 'Latvia', 'Letônia, Republica da', 'LV');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (120, 'Lebanon', 'Líbano', 'LB');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (121, 'Lesotho', 'Lesoto', 'LS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (122, 'Liberia', 'Libéria', 'LR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (123, 'Libyan Arab Jamahiriya', 'Líbia', 'LY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (124, 'Liechtenstein', 'Liechtenstein', 'LI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (125, 'Lithuania', 'Lituânia, Republica da', 'LT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (126, 'Luxembourg', 'Luxemburgo', 'LU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (127, 'Macau', 'Macau', 'MO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (128, 'North Macedonia', 'Macedônia do Norte', 'MK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (129, 'Madagascar', 'Madagascar', 'MG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (130, 'Malawi', 'Malavi', 'MW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (131, 'Malaysia', 'Malásia', 'MY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (132, 'Maldives', 'Maldivas', 'MV');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (133, 'Mali', 'Mali', 'ML');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (134, 'Malta', 'Malta', 'MT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (135, 'Marshall Islands', 'Marshall, Ilhas', 'MH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (136, 'Martinique', 'Martinica', 'MQ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (137, 'Mauritania', 'Mauritânia', 'MR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (138, 'Mauritius', 'Mauricio', 'MU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (139, 'Mayotte', 'Mayotte (Ilhas Francesas)', 'YT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (140, 'Mexico', 'México', 'MX');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (141, 'Micronesia, Federated States of', 'Micronesia', 'FM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (142, 'Moldova, Republic of', 'Moldávia, Republica da', 'MD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (143, 'Monaco', 'Mônaco', 'MC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (144, 'Mongolia', 'Mongólia', 'MN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (145, 'Montserrat', 'Montserrat, Ilhas', 'MS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (146, 'Morocco', 'Marrocos', 'MA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (147, 'Mozambique', 'Moçambique', 'MZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (148, 'Myanmar', 'Mianmar (Birmânia)', 'MM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (149, 'Namibia', 'Namíbia', 'NA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (150, 'Nauru', 'Nauru', 'NR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (151, 'Nepal', 'Nepal', 'NP');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (152, 'Netherlands', 'Países Baixos (Holanda)', 'NL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (154, 'New Caledonia', 'Nova Caledonia', 'NC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (155, 'New Zealand', 'Nova Zelândia', 'NZ');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (156, 'Nicaragua', 'Nicarágua', 'NI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (157, 'Niger', 'Níger', 'NE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (158, 'Nigeria', 'Nigéria', 'NG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (159, 'Niue', 'Niue, Ilha', 'NU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (160, 'Norfolk Island', 'Norfolk, Ilha', 'NF');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (161, 'Northern Mariana Islands', 'Marianas do Norte', 'MP');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (162, 'Norway', 'Noruega', 'NO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (163, 'Oman', 'Oma', 'OM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (164, 'Pakistan', 'Paquistão', 'PK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (165, 'Palau', 'Palau', 'PW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (166, 'Panama', 'Panamá', 'PA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (167, 'Papua New Guinea', 'Papua Nova Guine', 'PG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (168, 'Paraguay', 'Paraguai', 'PY');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (169, 'Peru', 'Peru', 'PE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (170, 'Philippines', 'Filipinas', 'PH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (171, 'Pitcairn', 'Pitcairn, Ilha', 'PN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (172, 'Poland', 'Polônia, Republica da', 'PL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (173, 'Portugal', 'Portugal', 'PT');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (174, 'Puerto Rico', 'Porto Rico', 'PR');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (175, 'Qatar', 'Catar', 'QA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (176, 'Reunion', 'Reunião, Ilha', 'RE');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (177, 'Romania', 'Romênia', 'RO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (178, 'Russian Federation', 'Rússia, Federação da', 'RU');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (179, 'Rwanda', 'Ruanda', 'RW');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (180, 'Saint Kitts and Nevis', 'São Cristovão e Neves, Ilhas', 'KN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (181, 'Saint LUCIA', 'Santa Lucia', 'LC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (182, 'Saint Vincent and the Grenadines', 'São Vicente e Granadinas', 'VC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (183, 'Samoa', 'Samoa', 'WS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (184, 'San Marino', 'San Marino', 'SM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (185, 'Sao Tome and Principe', 'São Tome e Príncipe, Ilhas', 'ST');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (186, 'Saudi Arabia', 'Arábia Saudita', 'SA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (187, 'Senegal', 'Senegal', 'SN');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (188, 'Seychelles', 'Seychelles', 'SC');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (189, 'Sierra Leone', 'Serra Leoa', 'SL');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (190, 'Singapore', 'Cingapura', 'SG');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (191, 'Slovakia (Slovak Republic)', 'Eslovaca, Republica', 'SK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (192, 'Slovenia', 'Eslovênia, Republica da', 'SI');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (193, 'Solomon Islands', 'Salomão, Ilhas', 'SB');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (194, 'Somalia', 'Somalia', 'SO');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (195, 'South Africa', 'África do Sul', 'ZA');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (196, 'South Georgia and the South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (197, 'Spain', 'Espanha', 'ES');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (198, 'Sri Lanka', 'Sri Lanka', 'LK');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (199, 'St. Helena', 'Santa Helena', 'SH');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (200, 'St. Pierre and Miquelon', 'São Pedro e Miquelon', 'PM');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (201, 'Sudan', 'Sudão', 'SD');
INSERT INTO tb_country (id, name, name_portuguese, code) VALUES (202, 'Suriname', 'Suriname', 'SR');

