# Dados de conexao com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:sql/h2/init.sql'
    username: sa
    password:

  batch:
    jdbc:
      initialize-schema: embedded
      schema: classpath:sql/batch/schema-h2.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
