spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bemparatodos
    username: admin
    password: admin

  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:sql/batch/schema-postgresql.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: update

