spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bemparatodos
    username: postgres
    password: ong034
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
