database:
  default:
    url: jdbc:h2:mem:default
    username: sa
    password: teste
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: create

# Dados de conexao com o banco H2
spring:
  # Configuracao do cliente web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console

